name: Build and deploy

# define the trigger
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      # We used "docs" as directory name for our documentation, we will be referencing this later
      working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      # Check out main branch
      - name: Checkout
        uses: actions/checkout@main

      # Downloads, configures and caches Node.js
      - name: Setup node env
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}

      # Install all dependencies needed to build our documentation
      - name: Install dependencies
        # Referencing our docs directory here
        working-directory: ${{env.working-directory}}
        run: npm i

      # The generate command is used to invoke Nuxt static site generation
      - name: Generate
        working-directory: ${{env.working-directory}}
        run: npm run generate
